project:
  title: "QGreenland Educator Workshop 2023"
  type: "website"
  render:
    - "*.qmd"
    - "*.md"
    - "!doc/"


website:
  title: "QGreenland Educator Workshop 2023"
  # description: TODO
  site-url: "https://qgreenland-workshop-2023-educator.github.io"

  repo-url: &repo-url "https://github.com/qgreenland-workshop-2023-educator/qgreenland-workshop-2023-educator.github.io"
  repo-actions: ["edit", "issue"]

  navbar:
    left:
      - text: "Prerequisites"
        file: "content/prerequisites/index.qmd"
      - text: "Schedule"
        file: "content/schedule.qmd"
      - text: "Materials"
        # TODO: Do we want a dedicated "materials" page? It's useful for the
        # researcher workshop because that page links out to slides, exercises,
        # etc., but this repo doesn't have those.
        file: "content/continued-learning.qmd"
    right:
      - icon: "github"
        aria-label: "GitHub"
        href: *repo-url

  # NOTE: This sidebar is configured for "hybrid navigation"; each sidebar
  # entry must match up with a navbar entry by:
  #   - `title` on sidebar entry matches `text` on navbar entry
  #   - First item in `contents` on sidebar entry matches `file` on navbar entry
  # >> https://quarto.org/docs/websites/website-navigation.html#hybrid-navigation
  # NOTE: The sidebar requires >1 entry to work in hybrid mode, or the same
  # sidebar will show up on every page.
  # >> https://github.com/quarto-dev/quarto-cli/issues/1853
  # NOTE: Sidebar disabled, it's not useful when there's just one item.
  # sidebar:
  #   - title: "Prerequisites"
  #     contents:
  #       - "content/prerequisites/index.qmd"
  #   - title: "Schedule"
  #     contents:
  #       - "content/schedule.qmd"
  #   - title: "Materials"
  #     contents:
  #       - "content/continued-learning.qmd"

  page-footer:
    left: "Built with [Quarto](https://quarto.org/) ❤️"
    right:
      - text: "Code of Conduct"
        href: "CODE_OF_CONDUCT.md"
      - text: "License"
        href: "LICENSE.md"


format:
  html:
    theme:
      light: "flatly"
      dark: "darkly"
    toc: true
